apiVersion: apps/v1
kind: Deployment
metadata:
  name: non-compliant-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: non-compliant-app
  template:
    metadata:
      labels:
        app: non-compliant-app
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: non-compliant-container
        image: nginx:latest
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add: ["ALL"]
          runAsUser: 0
        ports:
        - containerPort: 80
        env:
        - name: DB_PASSWORD
          value: "insecure-password-value"
        volumeMounts:
        - name: host-path
          mountPath: /host
      volumes:
      - name: host-path
        hostPath:
          path: /
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: non-compliant-app
  namespace: default
spec:
  selector:
    app: non-compliant-app
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer