apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-fedramp-checklist
  namespace: default
data:
  checklist.md: |
    # Linkerd Service Mesh FedRAMP Compliance Checklist

    ## Installation and Configuration
    
    - [ ] Linkerd installed with secure configuration settings
    - [ ] Control plane secured with mutual TLS
    - [ ] Modern TLS versions (1.2+) and secure cipher suites enforced
    - [ ] Access logging enabled for audit trail
    - [ ] Resource limits configured to prevent DoS
    - [ ] Control plane components run with least privilege
    - [ ] HA configuration for production deployments

    ## Authentication
    
    - [ ] Auto-mTLS enabled for all meshes services
    - [ ] Identity certificates properly configured with trusted root
    - [ ] Certificate validity period configured appropriately
    - [ ] Trust anchors securely managed
    - [ ] Certificate rotation periods configured appropriately
    - [ ] Certificate validation enabled

    ## Authorization
    
    - [ ] Default deny ServerAuthorization policies implemented
    - [ ] Service-to-service authorization based on identity
    - [ ] Network policies configured for cluster-wide protection
    - [ ] Path-based and method-based access controls
    - [ ] Attribute-based access control for fine-grained authorization
    - [ ] Regular authorization policy audit and review

    ## Network Security
    
    - [ ] Ingress configuration secured
    - [ ] External traffic properly routed through ingress
    - [ ] All services properly annotated for mesh inclusion
    - [ ] Traffic split configurations validated
    - [ ] Egress traffic controls implemented
    - [ ] Network resilience features enabled (retries, timeouts)

    ## Monitoring and Audit
    
    - [ ] Prometheus configured for metrics collection
    - [ ] Grafana dashboards for security monitoring
    - [ ] Linkerd dashboard secured and accessible
    - [ ] Alerts configured for security events
    - [ ] Audit logging retained for required period
    - [ ] Regular security scanning of service mesh configuration

    ## Container Security (NIST SP 800-204D)
    
    - [ ] Container images scanned for vulnerabilities
    - [ ] Immutable container configurations used
    - [ ] Pod security standards implemented
    - [ ] Kubernetes admission controls integrated with mesh policies
    - [ ] Container runtime security monitoring in place
    - [ ] Secure container registry with image signing

    ## Supply Chain Security (NIST SP 800-204D)
    
    - [ ] Verifiable builds for container images
    - [ ] Software Bill of Materials (SBOM) generated for container images
    - [ ] Trusted container sources with provenance validation
    - [ ] Container image signing and verification enabled
    - [ ] CI/CD pipeline security for mesh configuration
    - [ ] Supply chain security integrated with mesh controls

    ## Compliance Documentation
    
    - [ ] Service mesh architecture documented
    - [ ] Security controls mapped to FedRAMP requirements
    - [ ] Evidence of control implementation collected
    - [ ] Continuous monitoring strategy documented
    - [ ] Incident response procedures established
    - [ ] Configuration management procedures documented